extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier

rules:
  selector-class-pattern: null
  keyframes-name-pattern: null
  color-function-notation: null
  scss/at-import-partial-extension: null
  scss/at-extend-no-missing-placeholder: null
