extends:
  - stylelint-config-standard-scss
  - stylelint-config-prettier

rules:
  string-quotes: double
  selector-class-pattern: null
  keyframes-name-pattern: null
  color-function-notation: null
