import Review from '@/types/review';

const fakeDataReview: Array<Review> = [
  {
    id: 'aaaa1',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 1',
    stars: 3,
    content: 'truyen hay lam',
    date: '22/2/2001',
  },
  {
    id: 'aaaa2',
    userName: 'Nguyen Van Duong',
    bookName: 'jujutsu kaisen tap 2',
    stars: 1,
    content: 'truyen hay lam',
    date: '22/2/2021',
  },
  {
    id: 'aaaa3',
    userName: 'Nguyen Van Vo',
    bookName: 'jujutsu kaisen tap 3',
    stars: 5,
    content: 'truyen hay lam',
    date: '22/2/2022',
  },
  {
    id: 'aaaa4',
    userName: 'Nguyen Thi A',
    bookName: 'jujutsu kaisen tap 4',
    stars: 1,
    content: 'truyen hay lam',
    date: '22/4/2001',
  },
  {
    id: 'aaaa5',
    userName: 'Nguyen Thi Toan',
    bookName: 'jujutsu kaisen tap 5',
    stars: 3,
    content: 'truyen hay lam',
    date: '24/2/2001',
  },
  {
    id: 'aaa6a',
    userName: 'Nguyen Thi Su',
    bookName: 'jujutsu kaisen tap 6',
    stars: 3,
    content: 'truyen hay lam',
    date: '22/2/2033',
  },
  {
    id: 'aa7aa',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 7',
    stars: 3,
    content: 'truyen hay lam',
    date: '24/12/2022',
  },
  {
    id: 'aa8aa',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 8',
    stars: 3,
    content: 'truyen hay lam',
    date: '25/6/2001',
  },

  {
    id: 'aa9a1',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 9',
    stars: 3,
    content: 'truyen hay lam',
    date: '27/6/2001',
  },
  {
    id: 'aaa10',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 10',
    stars: 3,
    content: 'truyen hay lam',
    date: '28/2/2001',
  },
  {
    id: 'aaa11',
    userName: 'Ma Nguyen D',
    bookName: 'jujutsu kaisen tap 11',
    stars: 1,
    content: 'Truyen nay nhu cai qq',
    date: '28/2/2001',
  },
  {
    id: 'aaa12',
    userName: 'Huan Hoa Hong',
    bookName: 'jujutsu kaisen tap 12',
    stars: 3,
    content: 'truyen hay lam',
    date: '28/2/2001',
  },
  {
    id: 'aaa13',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 13',
    stars: 4,
    content: 'doi sukuna lau qua',
    date: '28/2/2001',
  },
  {
    id: 'aaa14',
    userName: 'Nguyen Van A',
    bookName: 'jujutsu kaisen tap 14',
    stars: 2,
    content: 'truyen nay can co nhieu nhan vat hon',
    date: '28/2/2001',
  },
  {
    id: 'aaa16',
    userName: 'Do Ngoc Anh Vien',
    bookName: 'jujutsu kaisen tap 16',
    stars: 2,
    content: 'truyen nay can co nhieu nhan vat hon',
    date: '28/2/2001',
  },
  {
    id: 'aaa17',
    userName: 'Huan Hoa Hong',
    bookName: 'jujutsu kaisen tap 17',
    stars: 5,
    content: 'khong doc cung thay hay',
    date: '28/2/2001',
  },
  {
    id: 'aaa18',
    userName: 'Ngo Van Ten',
    bookName: 'Tokyo Revenger tap 1',
    stars: 1,
    content: 'main simp qua',
    date: '28/2/2001',
  },
];

export default fakeDataReview;
