name: CI workflows
on:
  push:
    paths:
      - 'src/**'
      - 'index.ts'
      - 'src/index.ts'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and test
        run: |
          yarn 
          yarn test
        env:
          VITE_API: ${{ secrets.VITE_API }}
          VITE_apiKey: ${{ secrets.VITE_apiKey }}
          authDomain: ${{ secrets.authDomain }}
          projectId: ${{ secrets.projectId }}
          storageBucket: ${{ secrets.storageBucket }}
          messagingSenderId: ${{ secrets.messagingSenderId }}
          appId: ${{ secrets.appId }}
          measurementId: ${{ secrets.measurementId }}
          VITE_CLOUD_NAME: ${{ secrets.VITE_CLOUD_NAME }}
          VITE_UPLOAD_PRESET: ${{ secrets.VITE_UPLOAD_PRESET }}
          VITE_UploadAPI: ${{ secrets.VITE_UploadAPI }}
          VITE_databaseURL: ${{ secrets.VITE_databaseURL }}
          VITE_testAccount: ${{ secrets.VITE_testAccount }}
          VITE_testPassword: ${{ secrets.VITE_testPassword }}
          VITE_testUsername: ${{ secrets.VITE_testUsername }}
